import type { FamilyMember } from "../types";

export const graceReadingYear: FamilyMember = {
  id: "grace",
  name: "Grace",
  books: [
    {
      id: "one-golden-summer",
      title: "One Golden Summer",
      author: "Fortune, Carley",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1723652503l/217245639.jpg",
      dateFinished: "2025-11-04",
      rating: 4,
      pages: 352,
      genre: "Romance",
      goodreadsUrl: "https://www.goodreads.com/book/show/217245639-one-golden-summer",
    },
    {
      id: "the-four-winds",
      title: "The Four Winds",
      author: "Hannah, Kristin",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1594925043l/53138081.jpg",
      dateFinished: "2025-10-30",
      rating: 4,
      pages: 464,
      genre: "Historical Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/53138081-the-four-winds",
    },
    {
      id: "crooked-kingdom-six-of-crows-2",
      title: "Crooked Kingdom (Six of Crows, #2)",
      author: "Bardugo, Leigh",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1456172607l/22299763.jpg",
      dateFinished: "2025-10-18",
      rating: 4,
      pages: 546,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/22299763-crooked-kingdom",
    },
    {
      id: "onyx-storm-the-empyrean-3",
      title: "Onyx Storm (The Empyrean, #3)",
      author: "Yarros, Rebecca",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1720446357l/209439446.jpg",
      dateFinished: "2025-09-03",
      pages: 736,
      genre: "Fantasy / Romance",
      goodreadsUrl: "https://www.goodreads.com/book/show/209439446-onyx-storm",
    },
    {
      id: "summer-reading",
      title: "Summer Reading",
      author: "McKinlay, Jenn",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1665779154l/62339069.jpg",
      dateFinished: "2025-08-06",
      rating: 2,
      pages: 416,
      genre: "Romance",
      goodreadsUrl: "https://www.goodreads.com/book/show/62339069-summer-reading",
    },
    {
      id: "the-ocean-at-the-end-of-the-lane",
      title: "The Ocean at the End of the Lane",
      author: "Gaiman, Neil",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1497098493l/18505792.jpg",
      dateFinished: "2025-07-22",
      rating: 4,
      pages: 181,
      genre: "Fantasy",
      goodreadsUrl:
        "https://www.goodreads.com/book/show/18505792-the-ocean-at-the-end-of-the-lane",
    },
    {
      id: "the-hunting-party",
      title: "The Hunting Party",
      author: "Foley, Lucy",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1569862373l/37642030.jpg",
      dateFinished: "2025-07-25",
      rating: 2,
      pages: 336,
      genre: "Mystery & Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/37642030-the-hunting-party",
    },
    {
      id: "society-of-lies",
      title: "Society of Lies",
      author: "Brown, Lauren Ling",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1729005765l/202102003.jpg",
      dateFinished: "2025-07-17",
      rating: 3,
      pages: 400,
      genre: "Mystery & Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/202102003-society-of-lies",
    },
    {
      id: "the-favorites",
      title: "The Favorites",
      author: "Fargo, Layne",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1713149403l/211399784.jpg",
      dateFinished: "2025-11-11",
      rating: 4,
      pages: 384,
      genre: "Romance",
      goodreadsUrl: "https://www.goodreads.com/book/show/211399784-the-favorites",
    },
    {
      id: "bad-blood-the-naturals-4",
      title: "Bad Blood (The Naturals, #4)",
      author: "Barnes, Jennifer Lynn",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1477739068l/27424547.jpg",
      dateFinished: "2025-06-26",
      rating: 4,
      pages: 528,
      genre: "YA Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/27424547-bad-blood",
    },
    {
      id: "all-in-the-naturals-3",
      title: "All In (The Naturals, #3)",
      author: "Barnes, Jennifer Lynn",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1446265230l/24849026.jpg",
      dateFinished: "2025-06-23",
      rating: 5,
      pages: 400,
      genre: "YA Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/24849026-all-in",
    },
    {
      id: "killer-instinct-the-naturals-2",
      title: "Killer Instinct (The Naturals, #2)",
      author: "Barnes, Jennifer Lynn",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1391636942l/20409231.jpg",
      dateFinished: "2025-06-17",
      rating: 5,
      pages: 400,
      genre: "YA Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/20409231-killer-instinct",
    },
    {
      id: "the-naturals-the-naturals-1",
      title: "The Naturals (The Naturals, #1)",
      author: "Barnes, Jennifer Lynn",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1620015246l/13597723.jpg",
      dateFinished: "2025-06-15",
      rating: 5,
      pages: 320,
      genre: "YA Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/13597723-the-naturals",
    },
    {
      id: "the-water-keeper",
      title: "The Water Keeper",
      author: "Martin, Charles",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1562024995l/51342108.jpg",
      dateFinished: "2025-07-04",
      rating: 4,
      pages: 384,
      genre: "Christian Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/51342108-the-water-keeper",
    },
    {
      id: "the-last-one-at-the-wedding",
      title: "The Last One at the Wedding",
      author: "Rekulak, Jason",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1728476850l/203579177.jpg",
      dateFinished: "2025-06-14",
      rating: 3,
      pages: 352,
      genre: "Horror / Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/203579177-the-last-one-at-the-wedding",
    },
    {
      id: "kingdom-of-ash-throne-of-glass-7",
      title: "Kingdom of Ash (Throne of Glass, #7)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1673567331l/76715522.jpg",
      dateFinished: "2025-05-23",
      pages: 984,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/76715522-kingdom-of-ash",
    },
    {
      id: "tower-of-dawn-throne-of-glass-6",
      title: "Tower of Dawn (Throne of Glass, #6)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1673567264l/76714487.jpg",
      dateFinished: "2025-05-06",
      pages: 672,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/76714487-tower-of-dawn",
    },
    {
      id: "empire-of-storms-throne-of-glass-5",
      title: "Empire of Storms (Throne of Glass, #5)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1676979605l/76713323.jpg",
      dateFinished: "2025-05-06",
      pages: 720,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/76713323-empire-of-storms",
    },
    {
      id: "queen-of-shadows-throne-of-glass-4",
      title: "Queen of Shadows (Throne of Glass, #4)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1673566810l/76707900.jpg",
      dateFinished: "2025-02-11",
      pages: 672,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/76707900-queen-of-shadows",
    },
    {
      id: "heir-of-fire-throne-of-glass-3",
      title: "Heir of Fire (Throne of Glass, #3)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1673566654l/76706470.jpg",
      dateFinished: "2025-01-18",
      pages: 592,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/76706470-heir-of-fire",
    },
    {
      id: "the-assassin-s-blade-throne-of-glass-0-1-0-5",
      title: "The Assassin's Blade (Throne of Glass, #0.1-0.5)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1680869667l/126062562.jpg",
      dateFinished: "2025-01-02",
      pages: 464,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/126062562-the-assassin-s-blade",
    },
  ],
};
