import type { FamilyMember } from "../types";

export const momReadingYear: FamilyMember = {
  id: "mom",
  name: "Mom",
  books: [
    {
      id: "the-assassin-s-blade-throne-of-glass-0-1-0-5",
      title: "The Assassin's Blade (Throne of Glass, #0.1-0.5)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1680869667l/126062562.jpg",
      dateFinished: "2025-11-02",
      rating: 3,
      pages: 464,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/126062562-the-assassin-s-blade",
    },
    {
      id: "gwendy-s-magic-feather-the-button-box-2",
      title: "Gwendy's Magic Feather (The Button Box, #2)",
      author: "Chizmar, Richard",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1556730076l/45428419.jpg",
      dateFinished: "2025-10-07",
      rating: 5,
      pages: 224,
      genre: "Horror / Supernatural",
      goodreadsUrl:
        "https://www.goodreads.com/book/show/45428419-gwendy-s-magic-feather",
    },
    {
      id: "queen-of-shadows-throne-of-glass-4",
      title: "Queen of Shadows (Throne of Glass, #4)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/7994583-L.jpg",
      dateFinished: "2025-09-07",
      rating: 5,
      pages: 672,
      genre: "YA Fantasy",
      goodreadsUrl:
        "https://www.goodreads.com/book/show/23848145-queen-of-shadows",
    },
    {
      id: "heir-of-fire-throne-of-glass-3",
      title: "Heir of Fire (Throne of Glass, #3)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/9318480-L.jpg",
      dateFinished: "2025-08-09",
      rating: 5,
      pages: 592,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/20613470-heir-of-fire",
    },
    {
      id: "when-we-had-wings",
      title: "When We Had Wings",
      author: "Lawhon, Ariel",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/12973109-L.jpg",
      dateFinished: "2025-07-25",
      rating: 4,
      pages: 424,
      genre: "Historical Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/58966514-when-we-had-wings",
    },
    {
      id: "falling-upward-a-spirituality-for-the-two-halves-of-life",
      title: "Falling Upward: A Spirituality for the Two Halves of Life",
      author: "Rohr, Richard",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/7565863-L.jpg",
      dateFinished: "2025-07-21",
      rating: 4,
      pages: 199,
      genre: "Spirituality",
      goodreadsUrl: "https://www.goodreads.com/book/show/9464627-falling-upward",
    },
    {
      id: "crown-of-midnight-throne-of-glass-2",
      title: "Crown of Midnight (Throne of Glass, #2)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/14348029-L.jpg",
      dateFinished: "2025-06-06",
      rating: 5,
      pages: 448,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/17167166-crown-of-midnight",
    },
    {
      id: "never-flinch-holly-gibney-4",
      title: "Never Flinch (Holly Gibney, #4)",
      author: "King, Stephen",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/14825714-L.jpg",
      dateFinished: "2025-06-02",
      rating: 3,
      pages: 448,
      genre: "Horror / Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/214923863-never-flinch",
    },
    {
      id: "throne-of-glass-throne-of-glass-1",
      title: "Throne of Glass (Throne of Glass, #1)",
      author: "Maas, Sarah J.",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/13312488-L.jpg",
      dateFinished: "2025-05-21",
      rating: 5,
      pages: 432,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/7896527-throne-of-glass",
    },
    {
      id: "pachinko",
      title: "Pachinko",
      author: "Lee, Min Jin",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/8044605-L.jpg",
      dateFinished: "2025-05-05",
      rating: 4,
      pages: 490,
      genre: "Historical Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/42965773-pachinko",
    },
    {
      id: "bad-blood-the-naturals-4",
      title: "Bad Blood (The Naturals, #4)",
      author: "Barnes, Jennifer Lynn",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1466122951l/30635180.jpg",
      dateFinished: "2025-04-27",
      rating: 4,
      pages: 384,
      genre: "YA Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/30635180-bad-blood",
    },
    {
      id: "all-in-the-naturals-3",
      title: "All In (The Naturals, #3)",
      author: "Barnes, Jennifer Lynn",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1436376704l/25873191.jpg",
      dateFinished: "2025-04-06",
      rating: 4,
      pages: 384,
      genre: "YA Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/25873191-all-in",
    },
    {
      id: "ruthless-vows-letters-of-enchantment-2",
      title: "Ruthless Vows (Letters of Enchantment, #2)",
      author: "Ross, Rebecca",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1684911502l/150260787.jpg",
      dateFinished: "2025-03-15",
      rating: 3,
      pages: 419,
      genre: "YA Fantasy",
      goodreadsUrl: "https://www.goodreads.com/book/show/150260787-ruthless-vows",
    },
    {
      id: "the-housemaid-the-housemaid-1",
      title: "The Housemaid (The Housemaid, #1)",
      author: "McFadden, Freida",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/15105883-L.jpg",
      dateFinished: "2025-03-12",
      rating: 4,
      pages: 336,
      genre: "Psychological Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/60556912-the-housemaid",
    },
    {
      id: "station-eleven",
      title: "Station Eleven",
      author: "Mandel, Emily St. John",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1451446835l/20170404.jpg",
      dateFinished: "2025-03-02",
      rating: 4,
      pages: 336,
      genre: "Post-apocalyptic Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/20170404-station-eleven",
    },
    {
      id: "the-naturals-the-naturals-1",
      title: "The Naturals (The Naturals, #1)",
      author: "Barnes, Jennifer Lynn",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1620015212l/18517840.jpg",
      dateFinished: "2025-02-11",
      rating: 4,
      pages: 308,
      genre: "YA Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/13597723-the-naturals",
    },
    {
      id: "the-women",
      title: "The Women",
      author: "Hannah, Kristin",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/207915-L.jpg",
      dateFinished: "2025-02-04",
      rating: 4,
      pages: 480,
      genre: "Historical Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/149843203-the-women",
    },
    {
      id: "the-three-body-problem-remembrance-of-earth-s-past-1",
      title: "The Three-Body Problem (Remembrance of Earth's Past, #1)",
      author: "Liu, Cixin",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1415428227l/20518872.jpg",
      dateFinished: "2025-02-02",
      rating: 4,
      pages: 416,
      genre: "Science Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/20518872-the-three-body-problem",
    },
    {
      id: "a-study-in-scarlet-sherlock-holmes-1",
      title: "A Study in Scarlet (Sherlock Holmes, #1)",
      author: "Doyle, Arthur Conan",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/13405534-L.jpg",
      dateFinished: "2025-01-29",
      rating: 3,
      pages: 192,
      genre: "Mystery / Detective Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/102868.A_Study_in_Scarlet",
    },
    {
      id: "the-night-agent",
      title: "The Night Agent",
      author: "Quirk, Matthew",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/8797323-L.jpg",
      dateFinished: "2025-01-23",
      rating: 3,
      pages: 432,
      genre: "Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/40942609-the-night-agent",
    },
    {
      id: "the-wedding-people",
      title: "The Wedding People",
      author: "Espach, Alison",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1721919005l/177328214.jpg",
      dateFinished: "2025-01-20",
      rating: 4,
      pages: 384,
      genre: "Contemporary Fiction",
      goodreadsUrl: "https://www.goodreads.com/book/show/177328214-the-wedding-people",
    },
    {
      id: "the-river-we-remember",
      title: "The River We Remember",
      author: "Krueger, William Kent",
      coverImageUrl:
        "https://covers.openlibrary.org/b/id/13608892-L.jpg",
      dateFinished: "2025-01-18",
      rating: 4,
      pages: 421,
      genre: "Historical Fiction / Mystery",
      goodreadsUrl: "https://www.goodreads.com/book/show/65200462-the-river-we-remember",
    },
    {
      id: "never-lie",
      title: "Never Lie",
      author: "McFadden, Freida",
      coverImageUrl:
        "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1661428846l/62080187.jpg",
      dateFinished: "2025-01-11",
      rating: 3,
      pages: 304,
      genre: "Psychological Thriller",
      goodreadsUrl: "https://www.goodreads.com/book/show/62080187-never-lie",
    },
  ],
};
